version: '2'
services:
  discovery-server:
    image: mszarlinski/spring-petclinic-discovery-server
    container_name: discovery-server
    mem_limit: 256M
    ports:
     - 8761:8761

  config-server:
    image: mszarlinski/spring-petclinic-config-server
    container_name: configserver
    mem_limit: 256M
    links:
     - discovery-server
    depends_on:
      - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8888:8888

  customers-service:
    image: mszarlinski/spring-petclinic-customers-service
    container_name: customers-service
    mem_limit: 256M
    links:
     - config-server
     - discovery-server
     - tracing-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","configserver:8888","--timeout=60","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
    - 8081:8081

  visits-service:
    image: mszarlinski/spring-petclinic-visits-service
    container_name: visits-service
    mem_limit: 256M
    links:
     - config-server
     - discovery-server
     - tracing-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","configserver:8888","--timeout=60","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8082:8082

  vets-service:
    image: mszarlinski/spring-petclinic-vets-service
    container_name: vets-service
    mem_limit: 256M
    links:
     - config-server
     - discovery-server
     - tracing-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","configserver:8888","--timeout=60","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8083:8083

  api-gateway:
    image: mszarlinski/spring-petclinic-api-gateway
    container_name: api-gateway
    mem_limit: 256M
    links:
     - config-server
     - discovery-server
     - customers-service
     - visits-service
     - vets-service
     - tracing-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","configserver:8888","--timeout=60","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8080:8080

  tracing-server:
    image: mszarlinski/spring-petclinic-tracing-server
    container_name: tracing-server
    mem_limit: 256M
    links:
     - config-server
     - discovery-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","configserver:8888","--timeout=60","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 9411:9411

  admin-server:
    image: mszarlinski/spring-petclinic-admin-server
    container_name: admin-server
    mem_limit: 256M
    links:
     - config-server
     - discovery-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","configserver:8888","--timeout=60","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 9090:9090
